Feat#10 Issue 관련 기능 개발
Soft-Gallery/issue-management-backEnd pull request #12
Opened 2024-05-22 14:08 UTC by RaccHoon

## 💬리뷰 참고사항
이슈는 프로젝트와 관련된 유저가 프로젝트에 속한 이슈와 상호작용하는거라 아직 프로젝트 코드가 없어 미완성입니다.
프로젝트 코드가 좀 나오면 수정할게요.
아직 검색 기능 안만들어짐. 버그 있을거임. 시간 필드가 없어서 최신순으로 정렬 안됨.(사실 id 필드가 1부터 차례로 올라가서 대충 되긴 함)
빠르게 개발하느라 놓친 부분이 많을 텐데 일단 틀만 잡아놓고 객체지향에 맞게 디벨롭 하겠습니다.
일단 시나리오상 처음부터 끝까지 동작합니다.

<개발한 기능>
1. 이슈의 생성 및 생성 권한이 없는 유저 제한(현재는 Tester 롤을 가진 사람만 시행 가능)
2. 이슈의 상세 정보 확인 기능. 이때 이슈와 관련된 유저 등의 모든 세부 정보도 반환될 수 있도록 하였음
3. 모든 이슈 보기 기능. 이것도 마찬가지로 모든 정보를 반환
4. 특정한 상태의 이슈 검색 기능. 시나리오 상 필요함.
5. assignee 설정 및 issue 상태 변경. 이것 역시 권한이 있는 유저만 가능(현재는 PL)
6. 나에게 할당된 모든 이슈 검색 기능. 시나리오상 dev에게 필요
7. 이슈를 Fixed상태로 변경. 유저의 토큰을 받아 해당 유저가 이슈의 asignee인지 확인 후 진행
8. Tester가 자신이 reporter인 모든 이슈 조회할 수 있는 기능.
9. 이슈를 resolved 상태로 만들수 있는 기능. 이것 역시 유저의 토큰을 확인해 해당 유저가 reporter일 때만 가능
10. 이슈를 closed 상태로 만들 수 있는 기능

11. 몇몇 Entity와 DTO를 서로 전환시킬 수 있는 기능. User의 경우 password는 DTO에 담을 때는 쓰레기 값이 들어감.
=> 이건 잘 한 건지 모르겠음.

## #️⃣연관된 이슈
다른 부분 코드가 나오면 좀 더 마음 편하게 진행할 수 있을것 같아요
프론트 만들면 연결해 봅시다

2024-05-22 14:17 UTC, 1Kirl commented
프로젝트 CRUD는 내일 선호와 함께 뚝딱 만들어보겠습니다. 고생하셨습니다!!!

2024-05-22 14:18 UTC, 1Kirl approved these changes

2024-05-22 15:49 UTC, SHKim55 requested changes
Core Logic 구현을 위해서 노력하신 흔적이 보입니다. 고생 많으셨어요.
내일 한결이랑 같이 프로젝트 CRUD 구현할 때 참고할 만한 코드가 많이 보입니다. 잘 써먹을게요.

[중요] 태그가 붙은 리뷰는 승인 전에 꼭 읽어보고 답변을 해주셨으면 하니 답변이 붙는 대로 바로 승인하도록 하겠습니다.

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/config/SecurityConfig.java
> +                        .requestMatchers("/tester", "/issue/new").hasRole("TESTER")
Admin이면 /admin 이하 엔드포인트만 접근, PL이면 /pl 이하 엔드포인트만 접근하도록 만드는 코드인가요?

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/controller/Home.java
>  }
현재 Home controller는 테스트 용도로만 사용하는 controller인가요? 만약 맞다면 main 폴더가 아니라 test 폴더에 하위 파일로 넣어주면 더 좋을 것 같아요. 그게 아니라 별도의 기능이 따로 있는 거라면 댓글로 알려주세요.

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/controller/issue/IssueController.java
> +    @PostMapping("/new")
create 엔드포인트 /new 군요. Comment랑 Project도 비슷하게 맞추겠습니다.

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/controller/issue/IssueController.java
> +
PathVariable로 받는 값들은 프런트에서 모두 넣어준다고 가정하신거 같은데 맞나요?

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/dto/IssueDTO.java
> +    private Priority priority;
진행상태, 우선순위 필드 추가 좋습니다. 나중에 우선순위에 따른 정렬 기능도 구현하실건가요?

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/dto/IssueDTO.java
> +    public IssueDTO(final Long id, final String title, final String description, final UserDTO reporter,
User 객체를 모두 UserDTO로 받아 다형성을 활용하신 부분 아주 마음에 듭니다.

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/entity/IssueEntity.java
> +    private String fixerId;
Nullable로 변경하신 이유가 궁금합니다. assignee 혹은 fixer가 하나도 없는 경우에 대한 처리를 위해 만드신 것 같은데, 이 경우 DB에 빈 값이 저장될 수 있어 쿼리 처리 시 문제가 발생할 가능성이 있을 것 같습니다.

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/repository/IssueRepository.java
> +public interface IssueRepository extends JpaRepository<IssueEntity, Long> {
Long 변경 Good

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueService.java
> +import org.apache.catalina.User;
이건 어떤 기능을 하는 라이브러리인가요?

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueService.java
> +        }
Optional 객체의 Null type 처리를 RuntimeException으로 해결하셨군요. 나중에 제 코드를 보시면 아시겠지만 저는 ObjectNotFoundException이라는 custom exception 클래스를 만들어서 해결했는데 제 코드도 올라가면 이러한 예외처리 로직도 하나로 통일시키면 좋을 것 같아요.

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueService.java
> +        issueEntity.setPriority(issueDTO.getPriority()!=null ? issueDTO.getPriority() : Priority.MAJOR);
삼항연산자 마스터 김재훈...

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/Priority.java
> +    TRIVIAL
각 5개 우선순위의 부여 기준이 궁금합니다. 어떤 이슈가 TRIVIAL이고 어떤 이슈가 BLOCKER인지는 어떻게 판정하나요?

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/State.java
> +
한 줄 비워진거 불-편하니까 지워주세요

2024-05-22 15:49 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/user/UserService.java
> +        userEntity.getEmail(), "garbage", userEntity.getRole());
[중요]
Entity를 DTO로 만들 때 패스워드에 garbage 값을 넣게 되면 나중에 해당 DTO가 다시 Entity로 변환되는 경우가 있을 때 (ex. update 로직) 객체가 다시 DB에 들어가는 과정에서 문제가 생길 것 같은데 괜찮을까요?

2024-05-22 15:53 UTC, RaccHoon commented on src/main/java/com/softgallery/issuemanagementbackEnd/config/SecurityConfig.java
> +                        .requestMatchers("/tester", "/issue/new").hasRole("TESTER")
정확히 저 엔드포인트여야만 접근할 수 있을 거예요

2024-05-22 15:59 UTC, RaccHoon commented on src/main/java/com/softgallery/issuemanagementbackEnd/controller/Home.java
>  }
넵 그렇게 하든지 지우든지 할게요
근데 테스트 코드는 엄청 많이 짠 다음에 일부를 퍼 올려서 한꺼번에 돌린다고 알고 있는데 저 코드는 수 작업으로 테스트 해야 해서 그냥 지우는게 나을거 같아요. 컨트롤러 부분은 테스트가 크게 필요 없을것 같아서...

2024-05-22 16:00 UTC, RaccHoon commented on src/main/java/com/softgallery/issuemanagementbackEnd/controller/issue/IssueController.java
> +    @PostMapping("/new")
맞추면 보기 좋긴 한데 굳이 안 맞춰도 되긴 해요.
내가 알기론 명사로 적는게 원칙인걸로 알고 있음

2024-05-22 16:03 UTC, RaccHoon commented on src/main/java/com/softgallery/issuemanagementbackEnd/controller/issue/IssueController.java
> +
네 맞아요. 시나리오를 따라가면서 프론트가 가지고 있는 정보를 고려해서 짠 거라 잘 작동 할겁니다.
ex) 나에게 할당된 이슈 검색 -> 나에게 할당된 모든 이슈의 정보 반환 -> 사용자가 특정 이슈 클릭 -> 해당 이슈의 아이디를 같이 서버에 전송
이런 느낌

2024-05-22 16:04 UTC, RaccHoon commented on src/main/java/com/softgallery/issuemanagementbackEnd/dto/IssueDTO.java
> +    private Priority priority;
넵 할게요

2024-05-22 16:04 UTC, RaccHoon commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueService.java
> +        }
넵 말 그대로입니다.

2024-05-22 16:05 UTC, RaccHoon commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueServiceIF.java
> +    boolean createIssue(IssueDTO issueDTO, String token);
그것도 좋긴 한데 null값이 반환되는 경우가 있을까 걱정되네요

2024-05-22 16:08 UTC, RaccHoon commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/State.java
> +
의도한건 아닌데 원래 마지막줄 비우는게 국룰입니다

2024-05-22 16:15 UTC, SHKim55 commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/State.java
> +
앗ㅋㅋ 국룰을 몰랐구만

2024-05-22 16:18 UTC, RaccHoon commented on src/main/java/com/softgallery/issuemanagementbackEnd/service/user/UserService.java
> +        userEntity.getEmail(), "garbage", userEntity.getRole());
어차피 password 값을 디비에서 가져와도 암호화 된 텍스트라 Entity->DTO->Entity인 상황에서는 가비지 값과 다를 바가 없습니다.
업데이트 로직 같은 경우엔 사용자의 아이디를 이용해 entity를 찾아온 후 비밀번호는 따로 입력 받아 DTO 생성자로 DTO를 만드는 방법으로 해야 하지 않을까...

2024-05-22 16:21 UTC, SHKim55 approved these changes

2024-05-22 16:44 UTC, RaccHoon commented
Issue basic logic dev
Feat#10 -> dev

2024-05-22 16:44 UTC, merged

2024-05-23 10:29 UTC, RaccHoon commented on src/main/java/com/softgallery/issuemanagementbackEnd/entity/IssueEntity.java
> +    private String fixerId;
assignee와 fixer가 없을 때를 상정한거긴 한데 어떻게 하는게 좋을지 모르겠네요.
무언가 정해진 쓰레기 값을 넣던지 이렇게 하던지 해야 할 것 같은데 더 좋은 방법은 당장은 안떠오르네요